version: '3'

vars:
  NODE_BIN: ./node_modules/.bin

tasks:
  setup:
    desc: Install dependencies
    cmds:
      - npm install

  dev:
    desc: Start development server
    cmds:
      - npm run dev

  build:
    desc: Build the extension
    cmds:
      - npm run build

  preview:
    desc: Preview the build
    cmds:
      - npm run preview

  type-check:
    desc: Run TypeScript type checking
    cmds:
      - npx tsc --noEmit

  lint:
    desc: Run Biome lint
    cmds:
      - npx biome lint src

  lint-fix:
    desc: Run Biome lint and fix issues
    cmds:
      - npx biome lint src --apply

  format:
    desc: Run Biome format
    cmds:
      - npx biome format src --write

  test:
    desc: Run tests (Vitest)
    cmds:
      - npx vitest run

  check:
    desc: Run all quality checks
    cmds:
      - task: type-check
      - task: lint
      - task: test

  clean:
    desc: Clean build artifacts and dependencies
    cmds:
      - rm -rf dist
      - rm -rf node_modules
      - rm -rf coverage
